// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcfxwwvnc7pD_buEShfzkdAaR__9sRBrc',
    appId: '1:775046275764:web:037e0a1c4a7d4c5120ede1',
    messagingSenderId: '775046275764',
    projectId: 'minimal-login-app',
    authDomain: 'minimal-login-app.firebaseapp.com',
    storageBucket: 'minimal-login-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU7auiTuDBPTFf6OXlDt5JI2er-VdWSc',
    appId: '1:775046275764:android:7c811dce48ecae8d20ede1',
    messagingSenderId: '775046275764',
    projectId: 'minimal-login-app',
    storageBucket: 'minimal-login-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDzDL8m_RJIc97DK-3Riditgig3OTaoI',
    appId: '1:775046275764:ios:867415b8c3e1f3ad20ede1',
    messagingSenderId: '775046275764',
    projectId: 'minimal-login-app',
    storageBucket: 'minimal-login-app.appspot.com',
    iosBundleId: 'com.example.minimalLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDzDL8m_RJIc97DK-3Riditgig3OTaoI',
    appId: '1:775046275764:ios:d0918e298583db3720ede1',
    messagingSenderId: '775046275764',
    projectId: 'minimal-login-app',
    storageBucket: 'minimal-login-app.appspot.com',
    iosBundleId: 'com.example.minimalLoginApp.RunnerTests',
  );
}
